/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSalesRouteImport } from './routes/_app/sales'
import { Route as AppPurchasesRouteImport } from './routes/_app/purchases'
import { Route as AppProfileRouteImport } from './routes/_app/profile'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppDeliveriesRouteImport } from './routes/_app/deliveries'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppBillsRouteImport } from './routes/_app/bills'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app/categories/index'
import { Route as ApiPublicTumaCallbackRouteImport } from './routes/api/public/tuma-callback'
import { Route as AppProductsNewRouteImport } from './routes/_app/products/new'
import { Route as AppCategoriesNewRouteImport } from './routes/_app/categories/new'
import { Route as AppCategoriesIdRouteImport } from './routes/_app/categories/$id'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAccountsVendorsRouteImport } from './routes/_app/accounts/vendors'
import { Route as AppAccountsStaffRouteImport } from './routes/_app/accounts/staff'
import { Route as AppAccountsCustomersRouteImport } from './routes/_app/accounts/customers'
import { Route as AppProductsIdEditRouteImport } from './routes/_app/products/$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveriesRoute = AppDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicTumaCallbackRoute = ApiPublicTumaCallbackRouteImport.update({
  id: '/api/public/tuma-callback',
  path: '/api/public/tuma-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesNewRoute = AppCategoriesNewRouteImport.update({
  id: '/categories/new',
  path: '/categories/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIdRoute = AppCategoriesIdRouteImport.update({
  id: '/categories/$id',
  path: '/categories/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsVendorsRoute = AppAccountsVendorsRouteImport.update({
  id: '/accounts/vendors',
  path: '/accounts/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsStaffRoute = AppAccountsStaffRouteImport.update({
  id: '/accounts/staff',
  path: '/accounts/staff',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountsCustomersRoute = AppAccountsCustomersRouteImport.update({
  id: '/accounts/customers',
  path: '/accounts/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdEditRoute = AppProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/bills': typeof AppBillsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deliveries': typeof AppDeliveriesRoute
  '/invoices': typeof AppInvoicesRoute
  '/profile': typeof AppProfileRoute
  '/purchases': typeof AppPurchasesRoute
  '/sales': typeof AppSalesRoute
  '/accounts/customers': typeof AppAccountsCustomersRoute
  '/accounts/staff': typeof AppAccountsStaffRoute
  '/accounts/vendors': typeof AppAccountsVendorsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/categories/$id': typeof AppCategoriesIdRoute
  '/categories/new': typeof AppCategoriesNewRoute
  '/products/new': typeof AppProductsNewRoute
  '/api/public/tuma-callback': typeof ApiPublicTumaCallbackRoute
  '/categories/': typeof AppCategoriesIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/products/$id/edit': typeof AppProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/bills': typeof AppBillsRoute
  '/dashboard': typeof AppDashboardRoute
  '/deliveries': typeof AppDeliveriesRoute
  '/invoices': typeof AppInvoicesRoute
  '/profile': typeof AppProfileRoute
  '/purchases': typeof AppPurchasesRoute
  '/sales': typeof AppSalesRoute
  '/accounts/customers': typeof AppAccountsCustomersRoute
  '/accounts/staff': typeof AppAccountsStaffRoute
  '/accounts/vendors': typeof AppAccountsVendorsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/categories/$id': typeof AppCategoriesIdRoute
  '/categories/new': typeof AppCategoriesNewRoute
  '/products/new': typeof AppProductsNewRoute
  '/api/public/tuma-callback': typeof ApiPublicTumaCallbackRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/products/$id/edit': typeof AppProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/bills': typeof AppBillsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deliveries': typeof AppDeliveriesRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/accounts/customers': typeof AppAccountsCustomersRoute
  '/_app/accounts/staff': typeof AppAccountsStaffRoute
  '/_app/accounts/vendors': typeof AppAccountsVendorsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/categories/$id': typeof AppCategoriesIdRoute
  '/_app/categories/new': typeof AppCategoriesNewRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/api/public/tuma-callback': typeof ApiPublicTumaCallbackRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/products/$id/edit': typeof AppProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/bills'
    | '/dashboard'
    | '/deliveries'
    | '/invoices'
    | '/profile'
    | '/purchases'
    | '/sales'
    | '/accounts/customers'
    | '/accounts/staff'
    | '/accounts/vendors'
    | '/admin/users'
    | '/categories/$id'
    | '/categories/new'
    | '/products/new'
    | '/api/public/tuma-callback'
    | '/categories/'
    | '/products/'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/bills'
    | '/dashboard'
    | '/deliveries'
    | '/invoices'
    | '/profile'
    | '/purchases'
    | '/sales'
    | '/accounts/customers'
    | '/accounts/staff'
    | '/accounts/vendors'
    | '/admin/users'
    | '/categories/$id'
    | '/categories/new'
    | '/products/new'
    | '/api/public/tuma-callback'
    | '/categories'
    | '/products'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/bills'
    | '/_app/dashboard'
    | '/_app/deliveries'
    | '/_app/invoices'
    | '/_app/profile'
    | '/_app/purchases'
    | '/_app/sales'
    | '/_app/accounts/customers'
    | '/_app/accounts/staff'
    | '/_app/accounts/vendors'
    | '/_app/admin/users'
    | '/_app/categories/$id'
    | '/_app/categories/new'
    | '/_app/products/new'
    | '/api/public/tuma-callback'
    | '/_app/categories/'
    | '/_app/products/'
    | '/_app/products/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicTumaCallbackRoute: typeof ApiPublicTumaCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deliveries': {
      id: '/_app/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AppDeliveriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills': {
      id: '/_app/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/tuma-callback': {
      id: '/api/public/tuma-callback'
      path: '/api/public/tuma-callback'
      fullPath: '/api/public/tuma-callback'
      preLoaderRoute: typeof ApiPublicTumaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/new': {
      id: '/_app/categories/new'
      path: '/categories/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof AppCategoriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/$id': {
      id: '/_app/categories/$id'
      path: '/categories/$id'
      fullPath: '/categories/$id'
      preLoaderRoute: typeof AppCategoriesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/vendors': {
      id: '/_app/accounts/vendors'
      path: '/accounts/vendors'
      fullPath: '/accounts/vendors'
      preLoaderRoute: typeof AppAccountsVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/staff': {
      id: '/_app/accounts/staff'
      path: '/accounts/staff'
      fullPath: '/accounts/staff'
      preLoaderRoute: typeof AppAccountsStaffRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounts/customers': {
      id: '/_app/accounts/customers'
      path: '/accounts/customers'
      fullPath: '/accounts/customers'
      preLoaderRoute: typeof AppAccountsCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id/edit': {
      id: '/_app/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AppProductsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBillsRoute: typeof AppBillsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliveriesRoute: typeof AppDeliveriesRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppProfileRoute: typeof AppProfileRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppSalesRoute: typeof AppSalesRoute
  AppAccountsCustomersRoute: typeof AppAccountsCustomersRoute
  AppAccountsStaffRoute: typeof AppAccountsStaffRoute
  AppAccountsVendorsRoute: typeof AppAccountsVendorsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppCategoriesIdRoute: typeof AppCategoriesIdRoute
  AppCategoriesNewRoute: typeof AppCategoriesNewRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppProductsIdEditRoute: typeof AppProductsIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBillsRoute: AppBillsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeliveriesRoute: AppDeliveriesRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppProfileRoute: AppProfileRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppSalesRoute: AppSalesRoute,
  AppAccountsCustomersRoute: AppAccountsCustomersRoute,
  AppAccountsStaffRoute: AppAccountsStaffRoute,
  AppAccountsVendorsRoute: AppAccountsVendorsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppCategoriesIdRoute: AppCategoriesIdRoute,
  AppCategoriesNewRoute: AppCategoriesNewRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppProductsIdEditRoute: AppProductsIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicTumaCallbackRoute: ApiPublicTumaCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
